Move from Travis to GitHub Actions
requests/requests-oauthlib pull request #470
Opened 2021-11-24 08:19 UTC by JonathanHuot

As discussed in https://github.com/requests/requests-oauthlib/issues/460 and in https://github.com/requests/requests-oauthlib/pull/469, it seems simpler to use GitHub actions.

2021-11-24 17:23 UTC, JonathanHuot commented
I tested AndreMiras/coveralls-python-action, but found out important issue here https://github.com/AndreMiras/coveralls-python-action/issues/13

Coverage is passing and multiple github checks are added to the report, which is good. However, the data is pushed to coveralls as a "new coverage", i.e. we don't know if the coverage has increased or decreased compared to the master branch (base).

See as below 
![image](https://user-images.githubusercontent.com/820496/143284473-7d1eea62-efe7-4bd8-8628-2a7771811398.png)


I will move back to coverallsapp/github-action@master which was requiring a lcov format and not a standard format that coverage produce.

2021-11-25 07:24 UTC, JonathanHuot commented
So with the AndreMiras/coveralls-python-action I get https://coveralls.io/builds/44520842.
Limitation: I though https://github.com/AndreMiras/coveralls-python-action/issues/13 was a problem, but it seems I have the same behavior with the other one. I'm not sure at this stage if how can it be fixed.

When using the official coverallsapp/github-action I get https://coveralls.io/builds/44524845.
Limitation: CI is more complex due to the format required lcov
Limitation: python2.7 disabled 
Limitation: a change in the way coverage is calculated for property/setter compared to base.

2021-11-25 19:59 UTC, jtroussard commented
> I tested AndreMiras/coveralls-python-action, but found out important issue here [AndreMiras/coveralls-python-action#13](https://github.com/AndreMiras/coveralls-python-action/issues/13)
> 
> Coverage is passing and multiple github checks are added to the report, which is good. However, the data is pushed to coveralls as a "new coverage", i.e. we don't know if the coverage has increased or decreased compared to the master branch (base).
> 
> See as below ![image](https://user-images.githubusercontent.com/820496/143284473-7d1eea62-efe7-4bd8-8628-2a7771811398.png)
> 
> I will move back to coverallsapp/github-action@master which was requiring a lcov format and not a standard format that coverage produce.

Would the coverage comparison data not be shown if opening the "COVERAGE CHANGED" tab?

2021-12-03 19:05 UTC, jtroussard requested changes
Could we also inject a small doc/setup/getting started readme, specifically with the `tox` tool. I messed around with it for a while and could only get py2.7 stuff to work. I'm sure I'm screwing something up with the setup on my end.

### UPDATE
So for potential documentation, I found that running `tox -e <python-version-youre-working-with>` simplifiled the local replication process. Also when running manually, be sure to install both requirements files (there are three, depends on which version of python you're running in venv) ... `pip install -r requirements.txt && pip install -r requirements-test.txt` AND `pip install coveralls coverage-lcov toml`

2021-12-03 19:05 UTC, jtroussard commented on .github/workflows/run-tests.yml
> +      uses: coverallsapp/github-action@master
Not sure if this matters, but in my own repos I've had less problems when setting this value with an actual version number, I think 1.1.3 is latest stable:

```suggestion
      uses: coverallsapp/github-action@1.1.3
```

2021-12-03 19:05 UTC, jtroussard commented on .github/workflows/run-tests.yml
> +      uses: coverallsapp/github-action@master
```suggestion
      coverallsapp/github-action@1.1.3
```

2021-12-03 19:34 UTC, jtroussard commented on .github/workflows/run-tests.yml
> +        path-to-lcov: lcov.info
Ok nevermind mind this comment I misread one of the conditionals in the gh-actions workflow file and had a missing dependency when I was trying to rebuild this process by hand. Project root is the correct location.

```
    - name: Coverage format into lcov
      if: ${{ matrix.python-version != '2.7' }}
      run: |
        coverage-lcov --output_file_path lcov.info
```

2021-12-03 19:44 UTC, jtroussard commented
I think we can safetly add the following dependencies in `requirements-test.txt`:

- [ ] coverage-lcov
- [ ] toml

2021-12-06 20:24 UTC, JonathanHuot commented
> Could we also inject a small doc/setup/getting started readme, specifically with the `tox` tool. I messed around with it for a while and could only get py2.7 stuff to work. I'm sure I'm screwing something up with the setup on my end.
> ### UPDATE
> 
> So for potential documentation, I found that running `tox -e <python-version-youre-working-with>` simplifiled the local replication process. Also when running manually, be sure to install both requirements files (there are three, depends on which version of python you're running in venv) ... `pip install -r requirements.txt && pip install -r requirements-test.txt` AND `pip install coveralls coverage-lcov toml`

I have added a contributing guide, can you verify? Thanks!

2021-12-06 20:27 UTC, JonathanHuot commented
I'm parking the coverage question as of now, as we will need to see it in action with a couple of PRs to see if we can live with it or not. Anyway it should not be a blocker to start reviewing some PRs.

The PR is ready to be merged if review is OK!

2021-12-06 21:58 UTC, jtroussard approved these changes
lgtm

2021-12-06 21:59 UTC, jtroussard commented
looks good - let's confirm Github actions are working after this merge

2021-12-06 21:59 UTC, merged